% Use previously computed information about time-frequency
% target/interferer glimpses, stored in SimulationData, to process a
% different binaural signal (of equal length) for comparison
function enhancedSignal = enhanceComparisonSignal(type, inputSignal, ...
    SimulationData, AlgorithmStates, AlgorithmParameters)

switch type
    case 'target'
        AlgorithmParameters.Cancellation    = false;
        AlgorithmParameters.Enhancement     = true;
    case 'interf'
        AlgorithmParameters.Cancellation    = true;
        AlgorithmParameters.Enhancement     = false;
end

subbandTargetSignalArray = subbandDecompositionBinaural(inputSignal, ...
    AlgorithmStates);

enhancedSubbandSignalArray = harmonicEnhancementBinaural(...
            subbandTargetSignalArray, ...
            SimulationData.azimuthDegCells, ...
            SimulationData.ivsMaskCells, ...
            SimulationData.sigmaDesired, ...
            SimulationData.deltaDesired, ...
            SimulationData.snrDesired, ...
            SimulationData.p0DetectedIndexVectors, ...
            AlgorithmParameters);

enhancedSignal = subbandResynthesisBinaural(enhancedSubbandSignalArray, ...
    AlgorithmStates);

end