function enhancedSubbandSignals = ...
    harmonicCancellation(deconposedSubbandSignals, azimuth, ...
        sigmaDesired, deltaDesired, snrDesired)
enhancedSubbandSignals = deconposedSubbandSignals;
end