function [enhancedSignal, AlgorithmParameters] = ...
  speechEnhancement(inputSignal, AlgorithmParameters)

    enhancedSignal	= zeros(size(inputSignal));

    % Gammatone analysis filterbank
    [decomposedSubbandSignals.L, ...
        AlgorithmParameters.L.FilterStates.Gammatone.analyzer] = ...
        subbandDecomposition(inputSignal(:,1), ...
        AlgorithmParameters.L.FilterStates.Gammatone.analyzer);
    [decomposedSubbandSignals.R, ...
        AlgorithmParameters.R.FilterStates.Gammatone.analyzer] = ...
        subbandDecomposition(inputSignal(:,2), ...
        AlgorithmParameters.R.FilterStates.Gammatone.analyzer);
    
    % Periodicity analysis
    [sigmaDesired.L, deltaDesired.L, snrDesired.L] = ...
        periodicityAnalysis(decomposedSubbandSignals.L);
    [sigmaDesired.R, deltaDesired.R, snrDesired.R] = ...
        periodicityAnalysis(decomposedSubbandSignals.R);
    
    % DOA estimation
    azimuth = directionOfArrivalEstimation(decomposedSubbandSignals);
    
    % signal enhancement
    enhancedSubbandSignals = ...
        harmonicCancellation(decomposedSubbandSignals, azimuth, ...
            sigmaDesired, deltaDesired, snrDesired);

    % Gammatone synthesis filterbank
    [enhancedSignal(:,1), AlgorithmParameters.L.FilterStates.Gammatone.synthesizer] = ...
        subbandResynthesis(enhancedSubbandSignals.L, ...
        AlgorithmParameters.L.FilterStates.Gammatone.synthesizer);
    [enhancedSignal(:,2), AlgorithmParameters.R.FilterStates.Gammatone.synthesizer] = ...
        subbandResynthesis(enhancedSubbandSignals.R, ...
        AlgorithmParameters.R.FilterStates.Gammatone.synthesizer);
end