function enhancedSubbandSignalArray = ...
    harmonicCancellation(subbandSignalArray, azimuth, ...
        azDetectedIndexVectors, sigmaDesired, deltaDesired, snrDesired, ...
        p0DetectedIndexVectors, AlgorithmParameters, AlgorithmStates)

enhancedSubbandSignalArray = subbandSignalArray;
end